2025-04-18 19:35:19.304 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-18 19:35:19.305 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tplink_router which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-18 19:35:19.305 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-18 19:35:19.305 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tesla_custom which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-18 19:35:19.305 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ui_lovelace_minimalist which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-18 19:35:20.741 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.base] HACS Frontend repo "button-card" is already installed, Remove it or disable include custom cards
2025-04-18 19:35:20.742 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.base] HACS Frontend repo "light-entity-card" is already installed, Remove it or disable include custom cards
2025-04-18 19:35:20.742 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.base] HACS Frontend repo "lovelace-card-mod" is already installed, Remove it or disable include custom cards
2025-04-18 19:35:20.742 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.base] HACS Frontend repo "lovelace-auto-entities" is already installed, Remove it or disable include custom cards
2025-04-18 19:35:20.742 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.base] HACS Frontend repo "mini-graph-card" is already installed, Remove it or disable include custom cards
2025-04-18 19:35:20.742 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.base] HACS Frontend repo "mini-media-player" is already installed, Remove it or disable include custom cards
2025-04-18 19:35:20.742 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.base] HACS Frontend repo "simple-weather-card" is already installed, Remove it or disable include custom cards
2025-04-18 19:35:20.742 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.base] HACS Frontend repo "lovelace-layout-card" is already installed, Remove it or disable include custom cards
2025-04-18 19:35:20.742 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.base] HACS Frontend repo "lovelace-state-switch" is already installed, Remove it or disable include custom cards
2025-04-18 19:35:20.742 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.base] HACS Frontend repo "weather-radar-card" is already installed, Remove it or disable include custom cards
2025-04-18 19:35:21.521 ERROR (Thread-4) [pychromecast.socket_client] [Blue Speaker(0d85d3a4-8e74-3db6-5170-5fcffd27cc36.local.):8009] Failed to connect to service MDNSServiceInfo(name='Nest-Audio-0d85d3a48e743db651705fcffd27cc36._googlecast._tcp.local.'), retrying in 5.0s
2025-04-18 19:35:22.001 INFO (MainThread) [backoff] Backing off async_request(...) for 1.0s (tesla_wall_connector.exceptions.WallConnectorConnectionTimeoutError: Timeout while connecting to Wall Connector at 192.168.68.89)
2025-04-18 19:35:42.526 WARNING (MainThread) [homeassistant.components.sonos] Subscription to 192.168.68.75 failed, attempting to poll directly
2025-04-18 19:35:54.102 WARNING (MainThread) [homeassistant.components.nanoleaf] Received unknown touch gesture ID 0
2025-04-18 19:39:27.495 WARNING (Thread-9 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_2] is still running at shutdown: File "/usr/local/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 93, in _worker
    work_item.run()
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tplink_router/coordinator.py", line 58, in request
    data = callback()
  File "/usr/local/lib/python3.13/site-packages/tplinkrouterc6u/client/deco.py", line 82, in get_status
    data = self.request('admin/network?form=performance', dumps({"operation": "read"}))
  File "/usr/local/lib/python3.13/site-packages/tplinkrouterc6u/client/deco.py", line 158, in request
    return self._retry_request(super().request, path, data, ignore_response, ignore_errors)
  File "/usr/local/lib/python3.13/site-packages/tplinkrouterc6u/client/deco.py", line 164, in _retry_request
    return callback(*args)
  File "/usr/local/lib/python3.13/site-packages/tplinkrouterc6u/client/c6u.py", line 34, in request
    response = post(
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.13/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/local/lib/python3.13/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.13/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.13/socket.py", line 719, in readinto
    return self._sock.recv_into(b)
2025-04-18 19:39:28.491 WARNING (Thread-9 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_2] is still running at shutdown: File "/usr/local/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 93, in _worker
    work_item.run()
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tplink_router/coordinator.py", line 58, in request
    data = callback()
  File "/usr/local/lib/python3.13/site-packages/tplinkrouterc6u/client/deco.py", line 82, in get_status
    data = self.request('admin/network?form=performance', dumps({"operation": "read"}))
  File "/usr/local/lib/python3.13/site-packages/tplinkrouterc6u/client/deco.py", line 158, in request
    return self._retry_request(super().request, path, data, ignore_response, ignore_errors)
  File "/usr/local/lib/python3.13/site-packages/tplinkrouterc6u/client/deco.py", line 164, in _retry_request
    return callback(*args)
  File "/usr/local/lib/python3.13/site-packages/tplinkrouterc6u/client/c6u.py", line 34, in request
    response = post(
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.13/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/local/lib/python3.13/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.13/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.13/socket.py", line 719, in readinto
    return self._sock.recv_into(b)
